### ISSUE TITLE
Moure funcionalitat de InicioInterceptor a AuthenticationSuccessListener

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#129]
Numero: 169
Creació: 2015-04-17 08:23:56.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by jpernia-fundaciobit** [comment]
Fet
