### ISSUE TITLE
Temps excessiu al actualitzar oficines (RelacionesSIROFI.csv)

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#133]
Numero: 165
Creació: 2015-04-15 06:13:54.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by jpernia-fundaciobit** [comment]
Fet
