### ISSUE TITLE
DIR3CAIB: Errors JPA en la capa de model

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#156]
Numero: 141
Creació: 2015-03-06 07:10:12.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by kitanibaladmin** [comment]
2015-03-10 09:51:59

=============== FELIP ==================

Hi ha els errors de generador que estan solucionats.

La resta d'errors es produeixen a caus que hi ha un clau forania que apunta a un elemnt que forma part d'una clau primaria multiple. Cercant per internet et comenten que això no està bé i el que s'ha de fer és una única clau primaria autonumerica i el que eren les claus primaries fer un UNIQUE multiple.

Jo ho he provat i l'error desapareix, el problema és que necessitam afegir una nova columna a dues taules.

NOTA: Actualment Dir3Caib funciona o pareix que funciona.

**Comment by jpernia-fundaciobit** [comment]
Fet
