### ISSUE TITLE
Cron per inicialitzar comptadors

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#17]
Numero: 281
Creació: 2016-01-11 08:37:11.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by jpernia-fundaciobit** [comment]
Fet
