### ISSUE TITLE
Error en la pantalla para dar permisos sobre un Libro de registro

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#18]
Numero: 280
Creació: 2015-12-21 12:22:49.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by jpernia-fundaciobit** [comment]
Fet
