### ISSUE TITLE
Modificar plugin Custodia

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#19]
Numero: 279
Creació: 2015-12-17 13:13:51.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by jpernia-fundaciobit** [comment]
Fet
