### ISSUE TITLE
Afegir scripts de actualització de BD degut a la integració amb l'acarament

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#235]
Numero: 62
Creació: 2012-09-07 15:52:50.000
Permetre indicar el color del segell, que ara sempre és negre

**Comment by kitanibaladmin** [comment]
2012-09-12 09:29:07
Canvis als següents commits:

http://registre.svn.sourceforge.net/registre/?rev=110&view=rev
http://registre.svn.sourceforge.net/registre/?rev=111&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-12 10:50:35
faltava afegir el camp tipus.

http://registre.svn.sourceforge.net/registre/?rev=112&view=rev

Queda pendent fer les proves damunt postgres(12/09/12)

**Comment by kitanibaladmin** [comment]
2012-09-21 08:36:10
No sabem la causa però els scripts no estaven actualitzats amb els canvis d'acarament: http://registre.svn.sourceforge.net/registre/?rev=120&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-21 10:55:41
Faltava per mapejar la columna LOC_DOC

http://registre.svn.sourceforge.net/registre/?rev=123&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-21 11:31:06
Refer scripts de BBDD ja faltava el camp LOC_DOC de la taula BZDOCLOC: http://registre.svn.sourceforge.net/registre/?rev=124&view=rev

**Comment by jpernia-fundaciobit** [comment]
Fet
