### ISSUE TITLE
Afegir scripts de actualització de BD degut a la integració amb l'acarament

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#249]
Numero: 45
Creació: 2012-07-13 10:00:20.000
Revisar i sincronitzar canvis enviats per la DGTIC amb data 30-3-2010Changelog rebut de la DGTIC:             

S'ha afegit la següent funcionalitat i canvis:

  1- S'han solucionat els problemes de visualització al navegador IE.
(Modificació de les CSS)  
  2- S'ha solucionat un bug en la impressió del segell de registre, no
sortia el nom de l'oficina.  
  3- S'ha solucionat un bug en el visat dels canvis de remitent en els
registres de sortida  
  4- Creació d'oficines físiques "99" pel registres telemàtics. No es poden
utilitzar aquestes oficines per registres manuals. Aquesta opció es pot  
activar/desactivar al fitxer properties.  
 5-Solució del problema del títol de la finestra de remitents.  
 6-Gestió del número de documents registrats pels ajuntaments a través del 
conveni del 012. Aquesta opció es pot activar/desactivar al fitxer  
properties.  
 7- S'afegeix control del límit de registres per ofici + millora control  
dels errors al crear els oficis.  
 8- S'afegeix la visualització de les dades del BOIB als registres  
d'entrada de la oficina 32 (Funcionalitat per la CAIB).Aquesta opció es pot
activar/desactivar al fitxer properties.  
 9- Eliminació d'un bug en la gestió de la sessió de base de dades a les  
modificacions de registres.

**Comment by kitanibaladmin** [comment]
2012-07-17 10:38:27
Creada la carpeta 2.0 amb els scripts de creació de l'esquema.

http://registre.svn.sourceforge.net/registre/?rev=98&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-12 11:37:00
http://registre.svn.sourceforge.net/registre/?rev=114&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-20 10:24:23
Afegit script per postresql de l'actualització de 1.0 a 1.1

http://registre.svn.sourceforge.net/registre/?rev=116&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-21 09:11:26
No sabem la causa però els scripts no estaven actualitzats amb els canvis d'acarament: http://registre.svn.sourceforge.net/registre/?rev=121&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-21 10:54:50
faltava per mapejar la columna LOC_DOC.

http://registre.svn.sourceforge.net/registre/?rev=122&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-21 11:31:47
Refer scripts de BBDD ja faltava el camp LOC_DOC de la taula BZDOCLOC: http://registre.svn.sourceforge.net/registre/?rev=125&view=rev

**Comment by kitanibaladmin** [comment]
2012-09-21 11:45:11
Convertir script de creació de dades a UTF8: http://registre.svn.sourceforge.net/registre/?rev=126&view=rev

**Comment by jpernia-fundaciobit** [comment]
Fet
