### ISSUE TITLE
Arreglar Warnings 

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#294]
Adjunt un conjunt de warnings que m'apareixen en Elipse. Crec que estaria bé arreglar-los ja que alguns d'ells fan cridades a funcions i després no es fa res amb el resultat.

![warnings](https://cloud.githubusercontent.com/assets/14330416/15565625/4255f6ae-231c-11e6-8487-79bcdc95c577.png)

**Comment by jpernia-fundaciobit** [comment]
Fet
