### ISSUE TITLE
Substituir </br> per <br/>

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/registre#299]
S'ha de cercar per tot el codi html/jsp entrades del tipus </br> que no són correctes i reemplaçar-les per entrades <br/> que si ho són.

![error2](https://cloud.githubusercontent.com/assets/17084256/20338353/c7e404ee-abd6-11e6-9754-5847497069e7.png)

**Comment by mgonzalez-fundaciobit** [comment]
Fet.
