### ISSUE TITLE
Aspecto Alfresco

### ISSUE THREAD

**Issue by mmarinasamblea** [GovernIB/registre#310]
Buenos días, Les agradecería me indicasen si fuera posible, sobre la siguiente cuestión:

Dispone alguien de la implementación de Registre en su versión 3.0.5 funcionando con el plugin de custodia Alfresco?.

De ser así podrian facilitarme ayuda sobre la creación del Modelo, Tipos personalizados y aspectos utilizados.

Gracias.

**Comment by kitanibaladmin** [comment]
Buenas:

      Deberias enviar un correo a "otae @ fundaciobit.org" detallando quien eres, de que administración y más detalles de tu consulta.  Los ISSUES no deben utilizarse para consultas !!!!
