### ISSUE TITLE
Registro de salida con dos oficinas Origen

### ISSUE THREAD

**Issue by earrivi-fundaciobit** [GovernIB/registre#336]
Incidencia en un Registro de Salida que contiene dos oficinas origen, algo imposible según el modelo de datos.

Registro de salida L20S2694/2020: https://intranet.caib.es/regweb3/registroSalida/32967939/detalle

**Comment by jpernia-fundaciobit** [comment]
Es tanca l'issue perquè no s'ha pogut reproduir l'error, i l'oficina que ho va reportar ho ha tornat a generar i no han tengut cap problema.
