### ISSUE TITLE
Millora Coa de Distribució

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/registre#342]
Com a aplicació vull distribuir els assentaments de la coa de distribució de manera asíncrona per a que sigui més ràpid.

**Comment by mgonzalez-fundaciobit** [comment]
Aquest issue ja està fet, però de moment no se pasarà a pre i pro perque depen molt del comportament d'ArxiuCaib de l'entorn de PRO i s'han de fer moltes proves per estar segurs que realment és més ràpid i ara(CODIV-19) hi ha una gran càrrega de feina telemàtica i no és un moment oportú per fer aquestes proves. Se passara junt amb la millora de l'api d'arxiu.

**Comment by earrivi-fundaciobit** [comment]
Finalmente se descarta esta mejora. Cerramos la issue.
