### ISSUE TITLE
Evitar més de 9 permisos per usuari a un llibre

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/registre#368]
**Com a** desenvolupador de l'aplicació **vull** evitar que un usuari tengui més de 9 permisos damunt un llibre **per a que** la gestió sigui corecta i els llistats d'usuaris/permisos sigui correcta

**Comment by jpernia-fundaciobit** [comment]
S'han trobat llibres amb usuaris que tenen més de 9 permisos. Això fa que la seva gestió no sigui correcta i les consultes d'usuaris d'un llibre també sigui errònia.
Per solucionar el problema, mentre es troba la causa, es poden esborrar aquests usuaris, ja que esborra tots els seus permisos, i després donar-los d'alta i assignar els permisos correctes a cada llibre.

**Comment by earrivi-fundaciobit** [comment]
Cerramos la issue porqué con el cambio a Libro único ya no se producirá este error.
