### ISSUE TITLE
SIR: Adaptaciones mensajes rechazo SICRES 3.0

### ISSUE THREAD

**Issue by earrivi-fundaciobit** [GovernIB/registre#448]
SICRES 3.0 es la norma de interoperabilidad que define el intercambio registral entre las administraciones a través de la Plataforma SIR. SICRES 4.0 es una nueva versión de la norma que mejora dicha interoperabilidad y permite contemplar ciertas condiciones que la versión actual de la norma no permite. La tramitación para la aprobación de SICRES 4.0 se encuentra en un estado muy avanzado, por lo que pronto estará vigente, disponiendo, en su momento, de un período de un año para la adaptación de las aplicaciones certificadas a la nueva norma. Durante ese período de tiempo, convivirán en SIR aplicaciones que manejarán mensajes SICRES 3.0 y otras que manejarán mensajes SICRES 4.0.
Actualmente <b>el rechazo en SICRES 3.0 es un intercambio de registro</b> con toda la información incluidos los anexos. Uno de los cambios más destacados<b> en la norma SICRES 4.0 es que los mensajes de rechazo son enviados como mensajes 
de control</b>. </p>
<p>Con el objetivo de permitir la convivencia entre ambas normas e ir migrando de forma progresiva a la norma SICRES 4.0 se realizará una traducción de los mensajes de SICRES 3 a SICRES 4. Esta traducción será transparente para las 
instalaciones de las aplicaciones de registro ya que se realizará en el componente CIR de la Plataforma. </p>
<p>Para poder realizar esta traducción, <b>es necesario que las aplicaciones integradas dentro de la plataforma traten los rechazos ignorando la información relativa al registro</b>. Los campos que deben tratarse del mensaje de rechazo SICRES 3.0 son los siguientes:</p>

Etiqueta | Descripción | Tipo | Longitud | Obligación | Comentarios | Segmento  del mensaje
-- | -- | -- | -- | -- | -- | --
Codigo_Entidad_Registral_Origen | Código  Entidad Registral de Origen | Alfanumérico | 21 | Obligatorio | Código  único obtenido del Directorio Común. | De_Origen_o_Remitente
Codigo_Entidad_Registral_Destino | Código  Entidad Registral de destino | Alfanumérico | 21 | Obligatorio | Código  único obtenido del Directorio Común. | De_Destino
Identificador_Intercambio | Identificador  de Intercambio | Alfanumérico | 33 | Obligatorio | Identificador  de Intercambio único de la operación. | De_Internos_Control
Tipo_Anotacion | Tipo  de anotación | Alfanumérico | 2 | Obligatorio | En el  caso del mensaje de rechazo toma el valor 04 | De_Internos_Control
Descripcion_Tipo_Anotacion | Descripción  de anotación | Alfanumérico | 80 | Opcional | Motivo  de Rechazo. Obligatorio en el caso de un rechazo | De_Internos_Control
Numero_Registro_Entrada | Número  de registro | Alfanumérico | 20 | Opcional | Número  de registro asignado | De_Origen_o_Remitente

<p>Si la instalación de su aplicación de registro, al recibir un rechazo, trata 
más información de la indicada en la tabla deberán realizar las adaptaciones 
necesarias para no hacer uso del resto de información del mensaje, pues dejarán 
de recibirla cuando las aplicaciones de registro comiencen a migrarse al futuro 
SICRES 4. </p>
<p>Estos cambios deberán realizarse y estar disponibles en el entorno de 
producción <b>antes del 1 de noviembre de 2021. <br></b></p>
<p>Estamos a su disposición ante cualquier duda que le puedan suscitar los 
cambios a través del formulario de consultas de SIR en el siguiente enlace: <a href="https://ssweb.seap.minhap.es/ayuda/consulta/sir" moz-do-not-send="true">https://ssweb.seap.minhap.es/ayuda/consulta/sir</a><br></p></div></div>

**Comment by mgonzalez-fundaciobit** [comment]
Issue repetido SIR: Adaptaciones mensajes rechazo SICRES 3.0 #533. 
El #533 ya está hecho.
