### ISSUE TITLE
Cron  comportament extrany

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#70]
Numero: 228
Creació: 2015-07-08 11:34:04.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by kitanibaladmin** [comment]
2015-08-03 11:02:20
Sincronitzador ara borra Timers antics (http://sourceforge.net/p/dir3caib/code/78/)

**Comment by kitanibaladmin** [comment]
2015-08-07 10:47:08
S'han fet proves i el comportament del timer va be.
Si es troba aturat el jboss, reprograma el timer per el pròxim pic i elimina els que hi havia creats. També ho fa si reconfiguram la cronExpresion

**Comment by kitanibaladmin** [comment]
2015-08-10 08:33:55
Divendres va quedar programat el timer per dissabte. Avui dilluns en arrancar el jboss, ha eliminat el darrer timer, ha creat el següent per avui mateix, pero ha executat la sincronització automatica, es com si encara li quedas pendent el de dissabte i ho ha fet.

**Comment by jpernia-fundaciobit** [comment]
Fet
