### ISSUE TITLE
Desplegable "Organ" en interessats mostrar unitats arrels de les illes balears vigents

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#72]
Numero: 226
Creació: 2015-07-01 08:49:01.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by jpernia-fundaciobit** [comment]
Fet
