### ISSUE TITLE
RelacionesOrganizativasOfi no venen amb l'actualitzacio Entorn Producció dir3 Madrid

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/registre#74]
Numero: 224
Creació: 2015-06-30 06:45:40.000
Revisar i sincronitzar amb canvis rebuts de la DGTIC de 13-5-2011Changelog proporcionat per la DGTIC:                
- Cerca a les entrades per núm. sortida
- Memòria a les cerques
- Parametrització idioma per defecte a les entrades i sortides
- Millora consultes oficis
- Solució bug anulació oficis. Ja no els borra, si no que els marca com anul·lats com els registres.

**Comment by kitanibaladmin** [comment]
2015-11-23 10:00:06
Ja han reproduit l'error. I esta solventat a PRE. Quan estigui solventat a PRO ens avisaran.

+ info al correo dins otae del dia 11/11/2015 12:19

**Comment by jpernia-fundaciobit** [comment]
Fet
